; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = spiffs
build_flags =
  -I C:/Users/tolah/.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src
  -I C:/Users/tolah/.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src
lib_ldf_mode = deep+
lib_ignore =
  ESPAsyncTCP
  RPAsyncTCP
lib_deps =
  links2004/WebSockets

monitor_speed = 115200
upload_port = COM12
monitor_port = COM12
